//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bookings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub booking_id: Uuid,
    pub passenger_id: Option<Uuid>,
    pub booking_date: DateTime,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub total_amount: Decimal,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::passengers::Entity",
        from = "Column::PassengerId",
        to = "super::passengers::Column::PassengerId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Passengers,
    #[sea_orm(has_one = "super::performance_bookings::Entity")]
    PerformanceBookings,
    #[sea_orm(has_one = "super::restaurant_reservations::Entity")]
    RestaurantReservations,
    #[sea_orm(has_one = "super::travel_bookings::Entity")]
    TravelBookings,
}

impl Related<super::passengers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Passengers.def()
    }
}

impl Related<super::performance_bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerformanceBookings.def()
    }
}

impl Related<super::restaurant_reservations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantReservations.def()
    }
}

impl Related<super::travel_bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TravelBookings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
