//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "candidates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub candidate_id: Uuid,
    pub vacancy_id: Uuid,
    pub full_name: String,
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub cv_document: String,
    pub status: String,
    pub applied_at: DateTime,
    pub assigned_voyage: Option<String>,
    pub assigned_capacity: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::job_vacancies::Entity",
        from = "Column::VacancyId",
        to = "super::job_vacancies::Column::VacancyId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    JobVacancies,
}

impl Related<super::job_vacancies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JobVacancies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
