//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dining_tables")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub table_id: Uuid,
    pub restaurant_id: Option<Uuid>,
    pub table_number: String,
    pub capacity: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::restaurants::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurants::Column::RestaurantId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Restaurants,
}

impl Related<super::restaurants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
