//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "incidents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub incident_id: Uuid,
    pub incident_type: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub location: String,
    pub severity: String,
    pub status: String,
    pub resolved_at: Option<DateTime>,
    pub created_at: DateTime,
    pub submitted_by: Option<Uuid>,
    pub reviewed_by: Option<Uuid>,
    pub reviewed_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::medical_clearances::Entity")]
    MedicalClearances,
    #[sea_orm(has_one = "super::medical_incidents::Entity")]
    MedicalIncidents,
    #[sea_orm(has_one = "super::security_incidents::Entity")]
    SecurityIncidents,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ReviewedBy",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SubmittedBy",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users1,
}

impl Related<super::medical_clearances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalClearances.def()
    }
}

impl Related<super::medical_incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalIncidents.def()
    }
}

impl Related<super::security_incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecurityIncidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
