//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "linen_shortage_reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub report_id: Uuid,
    pub linen_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub severity: String,
    pub category: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub photo_data: Option<String>,
    pub reported_by: Option<Uuid>,
    pub reported_at: DateTime,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::linen_inventory::Entity",
        from = "Column::LinenId",
        to = "super::linen_inventory::Column::LinenId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LinenInventory,
    #[sea_orm(
        belongs_to = "super::user_accounts::Entity",
        from = "Column::ReportedBy",
        to = "super::user_accounts::Column::AccountId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UserAccounts,
}

impl Related<super::linen_inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinenInventory.def()
    }
}

impl Related<super::user_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
