//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "linen_inventory")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub linen_id: Uuid,
    #[sea_orm(unique)]
    pub item_name: String,
    pub stock_count: i32,
    pub threshold: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::linen_shortage_reports::Entity")]
    LinenShortageReports,
}

impl Related<super::linen_shortage_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinenShortageReports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
