//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "medical_incidents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub incident_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub known_conditions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub medications_on_file: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub treatment_given: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub outcome: Option<String>,
    pub clearance_issued: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::IncidentId",
        to = "super::incidents::Column::IncidentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Incidents,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
