//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod activities;
pub mod backup_logs;
pub mod bookings;
pub mod candidates;
pub mod dining_tables;
pub mod incidents;
pub mod job_vacancies;
pub mod linen_inventory;
pub mod linen_shortage_reports;
pub mod medical_clearances;
pub mod medical_incidents;
pub mod passenger_preferences;
pub mod passengers;
pub mod password_reset_requests;
pub mod performance_bookings;
pub mod performance_reports;
pub mod performances;
pub mod restaurant_reservations;
pub mod restaurants;
pub mod role_profiles;
pub mod roles;
pub mod seats;
pub mod security_incidents;
pub mod spending_entries;
pub mod system_logs;
pub mod travel_bookings;
pub mod user_accounts;
pub mod users;
pub mod zone_alerts;
pub mod zone_crew_assignments;
pub mod zones;
