//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "passengers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub passenger_id: Uuid,
    pub display_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub status: String,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub spending_balance: Decimal,
    pub vip_contact_channel: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bookings::Entity")]
    Bookings,
    #[sea_orm(has_many = "super::passenger_preferences::Entity")]
    PassengerPreferences,
    #[sea_orm(has_many = "super::spending_entries::Entity")]
    SpendingEntries,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::PassengerId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookings.def()
    }
}

impl Related<super::passenger_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PassengerPreferences.def()
    }
}

impl Related<super::spending_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpendingEntries.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
