//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "passenger_preferences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub preference_id: Uuid,
    pub passenger_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub cabin_preference: Option<String>,
    pub temperature: Option<String>,
    pub pillow_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub dietary_notes: Option<String>,
    pub preferred_newspaper: Option<String>,
    pub minibar_preference: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub special_requests: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::passengers::Entity",
        from = "Column::PassengerId",
        to = "super::passengers::Column::PassengerId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Passengers,
}

impl Related<super::passengers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Passengers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
