//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "performance_bookings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub booking_id: Uuid,
    pub performance_id: Option<Uuid>,
    pub seats: Option<Vec<String>>,
    pub is_vip_allocation: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bookings::Entity",
        from = "Column::BookingId",
        to = "super::bookings::Column::BookingId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bookings,
    #[sea_orm(
        belongs_to = "super::performances::Entity",
        from = "Column::PerformanceId",
        to = "super::performances::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Performances,
}

impl Related<super::bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookings.def()
    }
}

impl Related<super::performances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Performances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
