//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "performances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub performance_id: Uuid,
    pub title: String,
    pub venue_id: Uuid,
    pub schedule_date: Date,
    pub schedule_time: Time,
    pub actual_start_time: Option<Time>,
    pub actual_end_time: Option<Time>,
    pub status: String,
    pub current_occupancy: Option<i32>,
    pub total_capacity: i32,
    pub is_vip_window_open: Option<bool>,
    pub is_general_window_open: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::performance_bookings::Entity")]
    PerformanceBookings,
    #[sea_orm(has_many = "super::seats::Entity")]
    Seats,
}

impl Related<super::performance_bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerformanceBookings.def()
    }
}

impl Related<super::seats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
