//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "restaurant_reservations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub booking_id: Uuid,
    pub restaurant_id: Option<Uuid>,
    pub tables: Option<Vec<String>>,
    pub reservation_date: Date,
    pub reservation_time: Time,
    pub location: String,
    pub dietary_request: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bookings::Entity",
        from = "Column::BookingId",
        to = "super::bookings::Column::BookingId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bookings,
    #[sea_orm(
        belongs_to = "super::restaurants::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurants::Column::RestaurantId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Restaurants,
}

impl Related<super::bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookings.def()
    }
}

impl Related<super::restaurants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
