//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "restaurants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub restaurant_id: Uuid,
    pub restaurant_name: String,
    pub menu_type: String,
    pub deck: i32,
    pub capacity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dining_tables::Entity")]
    DiningTables,
    #[sea_orm(has_many = "super::restaurant_reservations::Entity")]
    RestaurantReservations,
}

impl Related<super::dining_tables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiningTables.def()
    }
}

impl Related<super::restaurant_reservations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantReservations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
