//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: Uuid,
    #[sea_orm(unique)]
    pub role_name: String,
    pub hierarchy_level: i32,
    pub department: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_profiles::Entity")]
    RoleProfiles,
    #[sea_orm(has_many = "super::user_accounts::Entity")]
    UserAccounts,
}

impl Related<super::role_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleProfiles.def()
    }
}

impl Related<super::user_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
