//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "seats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub seat_id: Uuid,
    pub performance_id: Option<Uuid>,
    pub seat_number: String,
    pub section: String,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::performances::Entity",
        from = "Column::PerformanceId",
        to = "super::performances::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Performances,
}

impl Related<super::performances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Performances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
