//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "spending_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub entry_id: Uuid,
    pub passenger_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub amount: Decimal,
    pub date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::passengers::Entity",
        from = "Column::PassengerId",
        to = "super::passengers::Column::PassengerId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Passengers,
}

impl Related<super::passengers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Passengers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
