//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "travel_bookings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub booking_id: Uuid,
    pub travel_agent_id: Option<Uuid>,
    pub departure_date: Date,
    pub cabin_category: String,
    pub itinerary_id: Uuid,
    pub add_ons: Option<Vec<String>>,
    pub cancellation_terms: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub commission_earned: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bookings::Entity",
        from = "Column::BookingId",
        to = "super::bookings::Column::BookingId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bookings,
}

impl Related<super::bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
