//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub display_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub password_salt: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_picture: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub bio: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backup_logs::Entity")]
    BackupLogs,
    #[sea_orm(has_many = "super::medical_clearances::Entity")]
    MedicalClearances,
    #[sea_orm(has_one = "super::passengers::Entity")]
    Passengers,
    #[sea_orm(has_many = "super::password_reset_requests::Entity")]
    PasswordResetRequests,
    #[sea_orm(has_many = "super::user_accounts::Entity")]
    UserAccounts,
}

impl Related<super::backup_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BackupLogs.def()
    }
}

impl Related<super::medical_clearances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalClearances.def()
    }
}

impl Related<super::passengers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Passengers.def()
    }
}

impl Related<super::password_reset_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordResetRequests.def()
    }
}

impl Related<super::user_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
