//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub profile_id: Option<Uuid>,
    pub is_active: Option<bool>,
    pub last_login: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub user_id: Uuid,
    pub role_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub employee_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::linen_shortage_reports::Entity")]
    LinenShortageReports,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::RoleId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Roles,
    #[sea_orm(has_many = "super::system_logs::Entity")]
    SystemLogs,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::zone_alerts::Entity")]
    ZoneAlerts,
    #[sea_orm(has_many = "super::zone_crew_assignments::Entity")]
    ZoneCrewAssignments,
}

impl Related<super::linen_shortage_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinenShortageReports.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::system_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemLogs.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::zone_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZoneAlerts.def()
    }
}

impl Related<super::zone_crew_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZoneCrewAssignments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
