//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "zone_alerts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub alert_id: Uuid,
    pub zone_id: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub sent_by: Uuid,
    pub sent_at: DateTime,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub recipients: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_accounts::Entity",
        from = "Column::SentBy",
        to = "super::user_accounts::Column::AccountId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserAccounts,
    #[sea_orm(
        belongs_to = "super::zones::Entity",
        from = "Column::ZoneId",
        to = "super::zones::Column::ZoneId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Zones,
}

impl Related<super::user_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAccounts.def()
    }
}

impl Related<super::zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Zones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
