//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "zones")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub zone_id: String,
    pub zone_name: String,
    pub passenger_density: String,
    pub activity_score: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::zone_alerts::Entity")]
    ZoneAlerts,
    #[sea_orm(has_many = "super::zone_crew_assignments::Entity")]
    ZoneCrewAssignments,
}

impl Related<super::zone_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZoneAlerts.def()
    }
}

impl Related<super::zone_crew_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZoneCrewAssignments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
